// This file is @generated by prost-build.
/// Command定义了对特定目标执行的命令
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Command {
    #[prost(oneof = "command::CmdPack", tags = "1, 2, 3")]
    pub cmd_pack: ::core::option::Option<command::CmdPack>,
}
/// Nested message and enum types in `Command`.
pub mod command {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum CmdPack {
        #[prost(message, tag = "1")]
        Conception(super::super::target::ConceptionCmd),
        #[prost(message, tag = "2")]
        Designation(super::super::designation::DesignCmd),
        #[prost(message, tag = "3")]
        Transform(super::super::transform::TransCmd),
    }
}
