// This file is @generated by prost-build.
/// Trailer消息用于在网络协议中标识消息长度和结构
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Trailer {
    /// 当前消息长度
    #[prost(uint32, tag = "1")]
    pub me: u32,
    /// 下一消息长度预期
    #[prost(uint32, tag = "2")]
    pub next: u32,
}
