// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DesignCmd {
    #[prost(oneof = "design_cmd::Cmd", tags = "1")]
    pub cmd: ::core::option::Option<design_cmd::Cmd>,
}
/// Nested message and enum types in `DesignCMD`.
pub mod design_cmd {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Cmd {
        #[prost(message, tag = "1")]
        Spawn(super::Spawn),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Spawn {
    #[prost(message, optional, tag = "1")]
    pub id: ::core::option::Option<super::target::TargetId>,
    #[prost(oneof = "spawn::Data", tags = "2, 3")]
    pub data: ::core::option::Option<spawn::Data>,
}
/// Nested message and enum types in `Spawn`.
pub mod spawn {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Data {
        #[prost(message, tag = "2")]
        FormatData(super::super::formats::FormatPack),
        #[prost(message, tag = "3")]
        ShapeData(super::super::shape::ShapePack),
    }
}
