// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FormatPack {
    #[prost(oneof = "format_pack::Data", tags = "1")]
    pub data: ::core::option::Option<format_pack::Data>,
}
/// Nested message and enum types in `FormatPack`.
pub mod format_pack {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Data {
        #[prost(message, tag = "1")]
        Image(super::Image),
    }
}
/// Image消息用于传输图像数据
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Image {
    /// 图像数据
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
