// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Resource {
    #[prost(oneof = "resource::Rsrc", tags = "1, 2")]
    pub rsrc: ::core::option::Option<resource::Rsrc>,
}
/// Nested message and enum types in `Resource`.
pub mod resource {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Rsrc {
        #[prost(message, tag = "1")]
        Format(super::super::formats::FormatPack),
        #[prost(message, tag = "2")]
        Shape(super::super::shape::ShapePack),
    }
}
