// This file is @generated by prost-build.
/// Shape定义了可用的几何形状类型
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ShapePack {
    #[prost(oneof = "shape_pack::Data", tags = "1, 2, 3, 4")]
    pub data: ::core::option::Option<shape_pack::Data>,
}
/// Nested message and enum types in `ShapePack`.
pub mod shape_pack {
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum Data {
        #[prost(message, tag = "1")]
        Point(super::Point),
        #[prost(message, tag = "2")]
        Segment(super::Segment),
        #[prost(message, tag = "3")]
        Sphere(super::Sphere),
        #[prost(message, tag = "4")]
        Cube(super::Cube),
    }
}
/// Pose定义了物体的位置、旋转和缩放信息
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Pose {
    #[prost(message, optional, tag = "1")]
    pub translation: ::core::option::Option<super::transform::Translation>,
    #[prost(message, optional, tag = "2")]
    pub rotation: ::core::option::Option<super::transform::Rotation>,
    #[prost(message, optional, tag = "3")]
    pub scale: ::core::option::Option<super::transform::Scale>,
}
/// PoseMatrix使用矩阵表示姿态变换
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PoseMatrix {
    /// 使用repeated代替array语法，更符合protobuf规范
    #[prost(float, repeated, tag = "1")]
    pub matrix: ::prost::alloc::vec::Vec<f32>,
}
/// Point表示一个三维点
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Point {
    #[prost(message, optional, tag = "1")]
    pub pos: ::core::option::Option<super::transform::Translation>,
}
/// Segment表示一条线段
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Segment {
    #[prost(message, optional, tag = "1")]
    pub start: ::core::option::Option<Point>,
    #[prost(message, optional, tag = "2")]
    pub end: ::core::option::Option<Point>,
}
/// Sphere表示一个球体
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Sphere {
    #[prost(message, optional, tag = "1")]
    pub pos: ::core::option::Option<super::transform::Translation>,
    #[prost(float, tag = "2")]
    pub radius: f32,
}
/// Cube表示一个立方体
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Cube {
    /// 统一使用translation字段名
    #[prost(message, optional, tag = "1")]
    pub translation: ::core::option::Option<super::transform::Translation>,
    /// 统一使用rotation字段名
    #[prost(message, optional, tag = "2")]
    pub rotation: ::core::option::Option<super::transform::Rotation>,
    /// 统一使用scale字段名
    #[prost(message, optional, tag = "3")]
    pub scale: ::core::option::Option<super::transform::Scale>,
}
