// This file is @generated by prost-build.
/// DesignID定义了设计元素的唯一标识符
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TargetId {
    /// 标识是否设置了ID
    #[prost(bool, tag = "1")]
    pub has_set: bool,
    /// 实际ID值
    #[prost(uint32, tag = "2")]
    pub id: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConceptionCmd {
    #[prost(oneof = "conception_cmd::Cmd", tags = "1")]
    pub cmd: ::core::option::Option<conception_cmd::Cmd>,
}
/// Nested message and enum types in `ConceptionCMD`.
pub mod conception_cmd {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Cmd {
        #[prost(message, tag = "1")]
        Id(super::TargetId),
    }
}
