// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TransCmd {
    #[prost(oneof = "trans_cmd::Trans", tags = "1, 2, 3")]
    pub trans: ::core::option::Option<trans_cmd::Trans>,
}
/// Nested message and enum types in `TransCMD`.
pub mod trans_cmd {
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum Trans {
        #[prost(message, tag = "1")]
        Translation(super::Translation),
        #[prost(message, tag = "2")]
        Rotation(super::Rotation),
        #[prost(message, tag = "3")]
        Scale(super::Scale),
    }
}
/// Translation定义了三维空间中的平移变换
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Translation {
    /// X轴坐标
    #[prost(float, tag = "1")]
    pub x: f32,
    /// Y轴坐标
    #[prost(float, tag = "2")]
    pub y: f32,
    /// Z轴坐标
    #[prost(float, tag = "3")]
    pub z: f32,
}
/// Rotation定义了三维空间中的旋转变换（欧拉角）
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Rotation {
    /// 绕X轴旋转角度
    #[prost(float, tag = "1")]
    pub rx: f32,
    /// 绕Y轴旋转角度
    #[prost(float, tag = "2")]
    pub ry: f32,
    /// 绕Z轴旋转角度
    #[prost(float, tag = "3")]
    pub rz: f32,
}
/// Scale定义了三维空间中的缩放变换
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Scale {
    /// X轴缩放因子
    #[prost(float, tag = "1")]
    pub sx: f32,
    /// Y轴缩放因子
    #[prost(float, tag = "2")]
    pub sy: f32,
    /// Z轴缩放因子
    #[prost(float, tag = "3")]
    pub sz: f32,
}
